#!/usr/bin/env python3
"""
This module contains an asynchronous function that collects random numbers
generated by an asynchronous generator into a list.
"""

import asyncio
async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> list:
    """
    Asynchronously collects 10 random numbers from async_generator into a list.

    Returns:
        list: A list of 10 random numbers generated asynchronously.
    """
    result = [i async for i in async_generator()]
    return result
